services:
  coupon-app:
    build: .
    container_name: coupon-app
    ports:
      - 8080:8080
    depends_on:
      coupon-db:
        condition: service_healthy
  #      redis-server:
  #        condition: service_healthy

  coupon-db:
    image: mysql
    container_name: coupon-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: coupon
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10

  #  coupon-redis:
  #    image: redis
  #    ports:
  #      - 6379:6379
  #    healthcheck:
  #      test: [ "CMD", "redis-cli", "ping" ]
  #      interval: 5s
  #      retries: 10

#  k6:
#    image: grafana/k6
#    container_name: k6
#    volumes:
#      - ./k6/scripts:/scripts      # load-test.js 위치
#      - ./k6/results:/results      # results.log 저장 위치
#    working_dir: /scripts
#    depends_on:
#      coupon-app:
#        condition: service_started
#    entrypoint: >
#      /bin/sh -c "k6 run load-test.js > /results/results.log 2>&1"

#  k6-1000:
#    image: grafana/k6
#    container_name: k6-1000
#    volumes:
#      - ./k6/scripts:/scripts      # load-test.js 위치
#      - ./k6/results:/results      # results.log 저장 위치
#    working_dir: /scripts
#    depends_on:
#      coupon-app:
#        condition: service_started
#    entrypoint: >
#      /bin/sh -c "k6 run load-test-1000-vus.js > /results/results.log 2>&1"

  k6-1000-nolock:
    image: grafana/k6
    container_name: k6-1000-nolock
    volumes:
      - ./k6/scripts:/scripts      # load-test.js 위치
      - ./k6/results:/results      # results.log 저장 위치
    working_dir: /scripts
    depends_on:
      coupon-app:
        condition: service_started
    entrypoint: >
      /bin/sh -c "k6 run load-test-1000-vus-nolock.js > /results/results.log 2>&1"

#  k6-1000-get:
#    image: grafana/k6
#    container_name: k6-1000-get
#    volumes:
#      - ./k6/scripts:/scripts      # load-test.js 위치
#      - ./k6/results:/results      # results.log 저장 위치
#    working_dir: /scripts
#    depends_on:
#      coupon-app:
#        condition: service_started
#    entrypoint: >
#      /bin/sh -c "k6 run load-test-1000-get.js > /results/results.log 2>&1"
