services:
  coupon-app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      coupon-db:
        condition: service_healthy
#      redis-server:
#        condition: service_healthy
  coupon-db:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: coupon
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10
#  coupon-redis:
#    image: redis
#    ports:
#      - 6379:6379
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 5s
#      retries: 10
