spring:
  datasource:
    url: jdbc:mysql://localhost:13306/coupon?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  profiles:
    active: local
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true        # SQL 출력
#        format_sql: true      # 예쁘게 출력
  jackson:
    property-naming-strategy: SNAKE_CASE
