spring:
  datasource:
    url: jdbc:mysql://coupon-db:3306/coupon
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: true        # SQL 출력
#        format_sql: true      # 예쁘게 출력

#  data:
#    redis:
#      host: redis-server
#      port: 6379
#      password: 1234
